# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      id: nvm
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    
    - name: Deploy application
      env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      run: |
          cd ~/
          git config --global user.email "fake2spam@gmail.com"
          git config --global user.name "viktorkim"
          git clone https://viktorkim:$DEPLOY_TOKEN@github.com/ViktorKim/viktorkim.github.io
          cd viktorkim.github.io
          rm -r ./prjctr-react-test-task
          cp -r /home/runner/work/prjctr-react-test-task/prjctr-react-test-task/build/* .
          git add .
          git commit -m "release from `date +%Y-%m-%d' '%H:%M:%S`"
          git push origin main
